### PR TITLE
Add Continuation to the chat

### PR DESCRIPTION
**Pull request by nokternol**
I have added three features:
1) display the text rendered using a view switch
2) record requests and responses allowing you to refine the requests
3) added a reset button to allow you to clear the stored conversation

Hope these are seen as improvements.
There is a fair bit of react and typescript improvements that can be made but I was more interested in playing with the requests.

### CODE REVIEW

**Comment by yuvalsuede** [comment]
@nokternol this is very nice, however - can you make it to keep the look and feel the same?
I see it does not keep the ui look of the original app, will appreciate if you can handle it

**Comment by nokternol** [comment]
The only changes to the look/feel are to add horizontal radios to switch from render to code
And a restart conversation/ session button.

Is this request to remove these items?

The restart session button would be required functionality.

**Review by yuvalsuede — APPROVED** [review]

**Comment by yuvalsuede** [comment]
@nokternol can you resolve conflicts?

**Comment by nokternol** [comment]
That will be an interesting challenge

**Comment by nokternol** [comment]
Simply put not in the few minutes I have available right now. You have added a feature in the middle of code I extracted to a custom hook. Reimplementing that code correctly will not be a short task and if I rush it I could break things.

**Comment by nokternol** [comment]
Okay, I have done the best I could at short notice to resolve. I will not be spending more time on it as this was 4 months ago. I hope it gets you close enough to consume the changes.

**Comment by nokternol** [comment]
no, it does not work and I am sorry but I no longer have the free time to troubleshoot it.

**Comment by nokternol** [comment]
Okay, it appears to be working it's quota and error handling issue
`You exceeded your current quota, please check your plan and billing details.`

**Comment by nokternol** [comment]
@yuvalsuede Please do not ask me to resolve anything more on this. If you do not merge it then just delete it.

**Review by yuvalsuede — APPROVED** [review]

**Pull request merged**
